name: 'Lucerne SPEAKS!'
favicon: null
layout_spectrum: 0.20638258242979646
typography_spectrum: 0.050567385740578175
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5159891652874649
  lightness: 0.060323386918753386
  saturation: 0.6753765780013055
  rhythmicContrast: 0.9244037715252489
purpose: []
