name: 'Lucerne SPEAKS!'
favicon: null
layout_spectrum: 0.20638258242979646
typography_spectrum: 0.050567385740578175
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#685d87'
    - '#a6a2b9'
    - '#100045'
    - '#172cfe'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
